### PR TITLE
Reduce and fix timeout/docs for SNMP requests

### LINKED ISSUE #507: SNMP Exporter Timeout
### Host operating system: output of `uname -a`

Linux hostname 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`
0.17.0

### What device/snmpwalk OID are you using?
We are walking lots of different devices/manufacturers (Mikrotik devices, Huawei switches, Ruckus wireless switches, Ruckus Wireless APs, Huawei APs, etcetera)

### What did you do that produced an error?

We are using curl to execute the query ourselves.

curl 'http://127.0.0.1:9116/snmp?target=10.1.32.110&module=mikrotik'
curl 'http://127.0.0.1:9116/snmp?target=10.1.32.110&module=huawei_switch'

### What did you expect to see?

We expect to see SNMP results. Most of the time, the queries succeed and we get back the data. Now and then (there's no correlation as to when it succeeds or fails), the SNMP query times out. Actually after taking packet captures, we see that the query is reaching the device, the device answers, but the response gets lost somewhere along the way. (These queries/replies are being sent over VPN tunnels over the public Internet.)

Due to the connectionless nature of UDP, we expect the SNMP exporter to send another query (after timeout interval of 10s, retries this 3 times; default values). 

### What did you see instead?

However, as you can see below, the snmp exporter doesn't send another query for 60 seconds:

Screenshot 2020-04-24 at 14 40 41

### PR DESCRIPTION
**Pull request by brian-brazil**
Upstream changed how their timeout&retries interacted, so
we no longer need to adjust things.

Our docs and code were also out of sync, but let's just reduce timeouts
to 2s as that should be plenty of time for a single GETBULK

Fixes #507

Signed-off-by: Brian Brazil <brian.brazil@robustperception.io>

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -47,7 +47,7 @@ var (
 		Version:        2,
 		MaxRepetitions: 25,
 		Retries:        3,
-		Timeout:        time.Second * 20,
+		Timeout:        time.Second * 2,
```
Comment (SuperQ) [inline config/config.go:50]: I'd suggest leaving this a little bit higher, maybe 5s. Some devices/networks are particularly slow.

Comment (brian-brazil) [reply config/config.go:50]: For a single GETBULK that's close on the network?

There is also an exponential option (which is what broke us) now that we could use.

Comment (brian-brazil) [reply config/config.go:50]: This is also a default, so if there's slow devices they could be configured by with a longer value without slowing down everyone who only loses a packet.

Comment (SuperQ) [reply config/config.go:50]: Yes, I think the default should be relatively relaxed for this kind of thing.

Comment (brian-brazil) [reply config/config.go]: Changed.
